### ISSUE TITLE
translate gender

### ISSUE THREAD

**Issue by ctlui** [lianglee/aboutuser#1]
Hi,
In https://github.com/lianglee/aboutuser/blob/d685f15de70fdc596c78c8ab7dbcc6f92e4a0286/plugins/default/profile/about.php#L23
Out is male or female can we get an ossn_print to have the value translated ?

Last one for the next 7 days as in 6 hours going at south France for beach holiday.

Thanks - Eric

**Comment by lianglee** [comment]
Good caught, i wasn't aware of this, yes we have to put these into langauge strings, ossn_print

It will be like:

```
<td><?php echo ossn_print("gender:{$params['user']->gender}");?></td>
```

**Comment by ctlui** [comment]
Hi

May be should be like below don't know if it's correct but it work

<code><td><?php echo ossn_print($params['user']->gender);?></td></code>

Computer goes in car now we are a little late :)

**Comment by lianglee** [comment]
Yes, will check it , have a nice holidays!
